### ISSUE TITLE
Text seems strange

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#11]
From Jari:

> 2.2.  Venue Selection Non-Objectives
>
> …
>
>    Maximal attendance:
>       Because the IETF garners a significant portion of its revenue from
>       IETF meeting fees, there is considerable incentive for decision-
>       makers to prefer a Venue that will attract more attendees.  It is
>       important to resist this temptation: a larger meeting in which key
>       contributors could not make it is not a better meeting; neither is
>       one with a lot of "tourists”.

This is correct, but sounds a bit strange. Maybe not the whole
truth.

I’d add “Yet, meetings need to be open and accessible for
both key contributors and others, including new contributors."

**Comment by eckelcu** [comment]
Eliot to reword to less offensive and inclusive.

**Comment by elear** [comment]
Reword as follows.

OLD:

>       Because the IETF garners a significant portion of its revenue from
>       IETF meeting fees, there is considerable incentive for decision-
>       makers to prefer a Venue that will attract more attendees.  It is
>       important to resist this temptation: a larger meeting in which key
>       contributors could not make it is not a better meeting; neither is
>       one with a lot of "tourists".

NEW (modulo formatting):

>               While the IETF strives to be as inclusive as possible
>               both online and in person, maximal
>               meeting attendance in and of itself is not a goal. It
>               would defeat a key goal of meeting if
>               active contributors with differing
>               points of view did not have the    opportunity to resolve their
>               disagreements, no matter how full the rooms.
