### ISSUE TITLE
Sponsor required as mandatory?

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#12]
From Jari:

>    +------------------------------------------------------+------------+
>    | The Venue is assessed as favorable for obtaining a   | "Mandatory |
>    | host and sponsors. That is, the Meeting is in a      | "          |
>    | location and at a price that it is possible and      |            |
>    | probable to find a host and sponsors.                |            |
>    +------------------------------------------------------+——————+

My personal opinion is that with increasing number of
large global corporations working on Internet tech, and
the IETF global host program, the reliance on finding
local hosts is reduced a bit. We still have to fight to find
sponsors and hosts, and if the meeting location is
somehow undesirable for sponsorship, that would be
an issue. But the text above could be interpreted
in different ways. I’m worried that we may not all
understand it the same. Does it assume a local
host model?

My suggestion would be to change text or downgrade
from mandatory.

**Comment by squarooticus** [comment]
How much does the local host help with logistics, and how much of that must be done, or is greatly aided, by the host being local?

**Comment by eckelcu** [comment]
Proposal to remove. Eliot to verify on list.
Funding/sponsorship issue may need to be added as a separate issue. Discuss this on list.

**Comment by elear** [comment]
Reminder, @squarooticus, that discussion occurs on list.
