### ISSUE TITLE
Handling repeats

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#13]
From Jari:

>    +------------------------------------------------------+------------+
>    | It is possible to enter into a multi-event contract  | "Desired"  |
>    | with the Venue to optimize meeting and attendee      |            |
>    | benefits, i.e., reduce administrative costs and      |            |
>    | reduce direct attendee costs, will be considered a   |            |
>    | positive factor. Such a contract can be considered   |            |
>    | after at least one IETF meeting has been held at the |            |
>    | Venue.                                               |            |
>    +------------------------------------------------------+------------+

Yes, support that.

But, I wonder if we’re hiding important things in the
details; cart before horse. In an so far unpublished
note that I’m writing on IASA 2.0, I had written
the following suggestion:

   Repetitive Meeting Schedule

      The IETF meeting cycle should move to a model where 5 meetings
      within a year are repeats in previously qualified hotels and
      locations, and at most 1 meeting is a new one.  The process for
      the previously qualified and new meetings shall be separated.  For
      instance, a contractor can be asked to arrange the repeat meetings
      with only approval for the final hotel agreement taken to the
      IAOC, and then more community and IAOC energy can be used to vet
      the new locations.

I’m not necessarily suggesting this exact model be adopted.
But if the document said “do repeats, and when you are
not repeating, THEN this complex set of requirements need
to be investigated”, maybe that would improve our process?

Note that the IAOC has pretty much gotten the point that the
community wants repeats. Looking from inside, the process
though is largely still the same for everything, which to me
seems wasting effort.

Of [those], it is not necessarily easy to “just repeat”, hotel availability
is a big issue for instance. I’ve been wanting to go back to Japan
for instance so many times already, but there are
challenges

**Comment by eckelcu** [comment]
Clarify city vs. facility

**Comment by elear** [comment]
In discussions, it seems that people were confused by the use of the term "Venue" here.  Thus, this is changed to IETF Hotel and Facility as follows:

>             It is possible to enter into a multi-event contract with the >>>Facility<<<
>             >>>and IETF Hotels<<< to optimize meeting and attendee benefits, i.e., reduce
>             administrative costs and reduce direct attendee costs, will be
>             considered a positive factor. Such a contract can be considered
>             after at least one IETF meeting has been held at the >>>Facility<<<.
