### ISSUE TITLE
Odd that accessibility requirements differ

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#14]
From Jari:

>    +-----------------------------------------------------+-------------+
>    | The Facility permits easy wheelchair access.        | "Mandatory" |
>    +-----------------------------------------------------+-------------+
>    | The Facility is accessible by people with           | "Important" |
>    | disabilities.                                       |             |
>    +-----------------------------------------------------+-------------+

1) Odd that the requirement levels differ

2) As an IAOC member I don’t have a clear understanding of what
to look for when assessing the second item.

**Comment by eckelcu** [comment]
Discussion was inconclusive. Leave text as is and lieu of a concrete proposal for how to change.

**Comment by elear** [comment]
This text still requires revision.  Alissa to send Eliot ptr to ICANN person covering accessibility.

**Comment by eckelcu** [comment]
Addressed by draft-07
