### ISSUE TITLE
Distinction between these two requirements?

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#15]
>    +-----------------------------------------------------+-------------+
>    | The Facility directly provides, or permits and      | "Mandatory" |
>    | facilitates, the delivery of a high performance,    |             |
>    | robust, unfiltered and unmodified IETF Network.     |             |
>    +-----------------------------------------------------+-------------+
>    | The IETF Hotel(s) directly provide, or else permit  | "Mandatory" |
>    | and facilitate, the delivery of a high performance, |             |
>    | robust, unfiltered and unmodified Internet service  |             |
>    | for the public areas and guest rooms; this service  |             |
>    | is typically included in the cost of the room.      |             |
>    +-----------------------------------------------------+——————+

I didn’t understand the distinction between these two items.

**Comment by eckelcu** [comment]
Eliot to check if network specifications draft covers and reference it.

**Comment by eckelcu** [comment]
Eliot indicated that "this was a misreading by all involved and should just be closed." I agree. Close as resolved.
Reference https://www.ietf.org/mail-archive/web/mtgvenue/current/msg01053.html
