### ISSUE TITLE
Whether the IAOC has executed a process step is not a criterion

### ISSUE THREAD

**Issue by coopdanger** [elear/mtgvenue#19]
One of the mandatory requirements in the document is listed as: 

"Available travel issue assessments ... have been pointed out the IETF community." 

This is not a criterion for meeting venue selection. Either this is a process step that the IAOC is expected to take and it should be included in the description of the process and taken for every venue, or it isn't. There shouldn't be criteria that depend solely on whether the IAOC executed its expected process.

**Comment by eckelcu** [comment]
Addressed by draft-07
