### ISSUE TITLE
Need a real decision tree

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#2]
From AJS

The first issue is the splitting of the criteria into so many
categories.  I don't understand the utility.  In terms of actually
making decisions, there are basically three divisions.  Criteria that
are mandatory cannot be traded no matter what, and therefore they
ought to be listed together.  Criteria that need to be traded off
need, well, to be traded off; so they ought to be listed together too.
All other criteria literally don't matter except as tie-breakers, so
the only reason to list them is to emphasise that certain things are
nicer to have than other ones.  The decision tree is a simple tree,
not a multidimensional one, so the additional dimension obscures
matters while adding nothing at all to decision-making.

A solution to this might be either to add another section that lists
the entire decision-rules in one place, or else to recast the category
listing as a single decision-rule table and then provide a
category-based breakout as an appendix or another section.

For instance, here are the criteria listed in decision-rule form (I
_think_ I got it all):

Mandatory: No Venue failure from community consultation, Venue
acceptable travel, Venue host and sponsors, Venue low barriers to
entry, Venue travel issue assessments, Facility size and layout,
Facility costs, Venue cash positive, Facility easy for wheelchairs,
Facility-techno support ok, Facility-techno network ok, Hotels-techno
network ok, Hotels proximity ok, Hotels number ok, Hotels contracts &
costs ok, Venue cheap hotels poss, Hotels wheelchairs ok, Venue
environs meal choices ok, Venue food restrictions ok.

Important: Venue disabilities ok, Hotels disabilities ok, HQ Hotel
lounge, Venue environs groceries.

Desired: Venue Multi-event contract, Facility one roof, Hotels
Internet ok.

**Comment by eckelcu** [comment]
Post to list for guidance to whether to leave organization as is or organize with most important first, etc.

**Comment by eckelcu** [comment]
Addressed by draft-07
