### ISSUE TITLE
s/IAOC/IASA?

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#20]
Brian Carpenter:

I just noticed a fundamental issue that affects both draft-ietf-mtgvenue-iaoc-venue-selection-process and draft-ietf-mtgvenue-meeting-policy.

They both keep referring to the IAOC as if it were an executive body. It isn't; it's an oversight committee. The executive body is the IASA, led by the IAD.

To a large extent this can fixed by a global s/IAOC/IASA/ in both documents. There may be some places where a little rephrasing is needed.

If you want to discuss the principle of what I'm saying, that belongs on the iasa20@ietf.org list. But under RFC4071, there really is no doubt that the executive body for meeting planning is IASA. The IAOC's role is overseeing the results.

**Comment by elear** [comment]
title was backwards!

**Comment by eckelcu** [comment]
Text proposed by Brian here https://mailarchive.ietf.org/arch/msg/mtgvenue/PYmO95AReestqYX3Aic31ZLcqfg

**Comment by eckelcu** [comment]
Proposed text added to draft-08
