### ISSUE TITLE
unfiltered should be mandatory

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#21]
From Alissa (trimmed for readibility):

Commenting as an individual below ...

>     The IETF Hotel(s) directly provide, or else permit…
The full text of this one is:

The Facility directly provides, or permits and facilitates, the delivery of a high performance, robust, unfiltered and unmodified IETF Network.

Personally I think this should be a mandatory criterion, i.e. we should not select a venue that cannot provide this. If this needs to reference the meeting network requirements document to provide the objective criteria by which it will be judged, that would be fine, I think.

**Comment by jordipalet** [comment]
I've agreed with Jim Martin, from the IETF NOC, to revive https://tools.ietf.org/html/draft-palet-ietf-meeting-network-requirements, now with the "on-site" information that I got from the site-survey-team in our survey of 8 venues a couple of weeks ago.

So we can use that as a pointer, however, even if I will try my best to do this very quickly, it may depend on inputs from others to get that document moving forward.

This document right now has a very basic text for this:
No content filtering or ACLs and consequently must not must not be
   prohibit end-to-end connectivity to any external sites.

So meanwhile, if a non-normative reference is not enough, we may use something such as:
The Facility directly provides, or permits and facilitates, the delivery of a high performance, robust, unfiltered and unmodified IETF Network, as described in the "technical details for IETF plenary meeting venue selection" (work in progress).

Alternatively, we can point out to https://iaoc.ietf.org/ietf-network-requirements.html ?

**Comment by elear** [comment]
Two requirements: one mandatory, one important, to address discussion on the list.  Some introductory text as well.

**Comment by mcr** [comment]
Go for the iaoc document reference.

**Comment by eckelcu** [comment]
Addressed by draft-07
