### ISSUE TITLE
freedom of expression

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#22]
From Jordi:

Section 2.1 point 2, should include “freedom of expression for the participants”.

**Comment by yoavnir** [comment]
Freedom of expression to what extent?   Anti-blasphemy laws and hate speech laws exist in in Canada, Australia, Brazil, and many countries in Europe. Do we disqualify all of them?

OTOH I don't think even in a North Korea meeting would anyone be restricting from voicing a technical opinion.  

So what are we trying to accomplish with this?

**Comment by jordipalet** [comment]
I think this text maybe makes it:

Avoid meeting in countries with laws that effectively exclude people on the basis of race, religion, gender, sexual orientation, national origin, or gender identity, or may disallow freedom of speech at the Facilities for any of the participants or even may force the shutdown Internet access.

**Comment by eckelcu** [comment]
No consensus on what, if anything to add. Closing.
Reference https://www.ietf.org/mail-archive/web/mtgvenue/current/msg01053.html
