### ISSUE TITLE
More than 1 hq hotel?

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#24]
From Jordi:

The IETF Headquarters Hotel has a space for use as a lounge …” This text need to be rewritten, as it is assuming that there is only one “headquarter” hotel. What if we have 4 as main hotels, because among them fulfill our needs?

**Comment by jordipalet** [comment]
Maybe this works:
The IETF meeting facilities, the Headquarters Hotel, or the combination of all them, in cases where there are several “official” facilities/hotels involved in the meeting, has a space for use as a lounge, conducive to planned and accidental meetings and chatting, as well as working online. 
There are tables with seating, convenient for small meetings with laptops. The can be at an open bar or casual restaurant. Preferably the lounge area is on the path between the meeting rooms and the hotel entrance, and is available all day and night.

**Comment by eckelcu** [comment]
"More than 1 hq hotel?": Sounds like Jordi's suggestion of "At least one of the IETF meeting facilities has a space for use as a lounge..." has made folks sufficiently happy to resolve this one. Let's update the text and then close.

**Comment by eckelcu** [comment]
Addressed by draft-07
