### ISSUE TITLE
Local support

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#25]
From Jordi:

I think it will be VERY important to have a local, which is also involved in the IETF, and knows the venue and the neighborhood of the facilities being evaluated, to help the on-site survey team. This could be added to 5.3 Qualification

**Comment by jordipalet** [comment]
I think we can make it with this text:
5.3 e.
It is very important that before the site qualification visit is arranged, a local to that venue, which is knowledgeable of the facilities and the neighborhood and is a frequent IETF participant, is engaged with the secretariat to assist them during the visit.

**Comment by elear** [comment]
Proposed alternative:


> When a new city is being considered, it is helpful to have someone who is familiar with both the locale and the IETF.  For example, such a person can provide guidance regarding safety, location of local services, and understanding best ways to get to and from the Venue.

**Comment by eckelcu** [comment]
Addressed by draft-07
