### ISSUE TITLE
Too much mandatory

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#3]
From AJS:

[There are] an enormous number of "Mandatory" and not very many
things that can be traded off, let alone things that are just nice to
have.  (It's also interesting that one of the "nice to haves" has been
the reason given to me not even to look at a number of places in the
explanations, so I'm not convinced that reflects actual practice.
That's a separate problem.) But if you look carefully at the Mandatory
cases, I think they're not all really Mandatory.  For instance (I'm
picking just one at random, so that this is the example isn't
significant):

   Travel to the Venue is acceptable based on cost,
   time, and burden for participants traveling from
   multiple regions. It is anticipated that the burden
   borne will be generally shared over the course of 
   multiple years. 

The problem is, if I am evaluating that, I don't know what "is
acceptable" means.  It's either empty (because, by definition, if
people show up the cost was acceptable) or else it's waving away the
contentiousness around "acceptable".  More importantly, since this
explicitly says that it's to be shared over the course of years, it's
actually an Important, and not Mandatory, item.

This is part of the reason I noted the other day that I just couldn't
tell whether the distinction Alissa and I had previously tried to make
is captured in the draft.  I believe that the various inconveniences
of informal travel restrictions that make visa-granting a crapshoot
are to be traded off, because we need to be prepared for the
possibility that people of one country or another are going to get
jerked around in any Venue.  At the same time, I believe that formal
bans against some class of people where that ban is not empirically
founded ought to be complete disqualifiers.  Legal restrictions on
(say) Upper Slobbovians or L-chromosome carriers are not ok and we
should eschew such sites.  Informal restrictions that turn out this
year to be capriciously applied against Lower Sobbovians and
M-chromosome carriers are not ok and are to be deplored, but are
predictable consequences of going from country to country.

I therefore think that a very serious look at what is Mandatory vs
Somethingelse is needed, with a view to reducing the Mandatory list.
Anything that has tradeoffs in it is automatically not Mandatory.
Anything else that seems to have room for wiggle is similarly not
really "Mandatory" except in the sense that there is some floor below
which the IAOC's judgement should say, "This is too onerous."

At bottom, that latter issue may be my real concern, because the
"Mandatory" list seems to offer a false objectivity.  The items are
all Mandatory, but since many of them involve descriptions that invoke
an enormous amount of judgement they're not really mandatory in the
English sense of the word at all.  They're important, and they're also
Important in the sense this draft describes.  They can be balanced
against one another, in a way that (for instance) a Venue actually having
enough meeting rooms and having them close enough to each other to
permit a meeting just cannot.  We _can't_ have a meeting without this
one:

    The Facility is adequate in size and layout to
    accommodate the meeting and foster participant
    interaction.

We maybe _could_ have a meeting without this one, but it might be
smaller:

    The cost of guest rooms, meeting space, meeting
    food and beverage is affordable, within the norms
    of business travel.
    
And we totally could have a meeting without this one, because we've in
fact done it (unless "allow" here is construed to mean "logically
possible):

    The economics of the Venue allow the meeting to be
    net cash positive.

Note that I'm particularly worried about all these Mandatories because
of §5.4 a.

**Comment by eckelcu** [comment]
Start by defining clearly what "Mandatory" means.
Revisit list of mandatories, categorizing as important by default, and argue individually for any that are to be mandatory. Constrain mandatory requirements as much as possible. Eliot to make initial recategorization.

**Comment by elear** [comment]
As mentioned by the chair, I am downgrading requirements based on working group discussion, mostly from Mandatory to Important.  As a reminder, the words are intended to be used consistent with their plain meaning.  That is- just because something is now Important specifically does not mean that it is UNimportant. 

From Mandatory to Important:

    Travel to venue is acceptable based on cost...
    The venue is assessed as favorable for obtaining...
    Travel barriers and visa requirements...
    Economic, safety, health...
    Facility support technology and services...
    Facility directly provides or permits...
    The IETF Hotel(s) directly provide, or else permit...
    The guest rooms at the IETF Hotel(s) are sufficient...
    The Venue environs, which includes both onsite, as...
    A range of attendee's health-related and religion...
    Overflow Hotels can be placed under contract...
    The Venue environs include budget hotels within...
    There are sufficient places (e.g., a mix of hallways, bars, meeting rooms, and restaurants) for people to hold ad hoc conversations and group discussions.
    (This last one is split out from a Mandatory)

Several requirements are removed based on the discussion.  They include the following:

    Available travel issue assessments -- such as...
    This requirement is to be moved into Section 5.
    The economics of the Venue allow the meeting to be...

This leaves but three mandatory requirements as follows:

    Consultation with the IETF Community has not produced concerns sufficient to disqualify the Venue.
    This requirement should probably turn into normative text in Section 5.
    The Facility is assessed to be able to provide sufficient space in an appropriate layout to accommodate the expected number of people to attend that meeting. (reworded to be clear as to what is mandatory)
    The Facility permits easy wheelchair access.
    Based on discussion in the room.

Eliot
