### ISSUE TITLE
Process innovation

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#4]
From AJS:

I don't know whether I've just not made this clear, or whether the
editors really disagree with me, but §4.1 appears to me to suggest
that we have a standard IETF consensus call about many issues related
to venues, and combined with the "is acceptable" language in §3 looks
to me like an enormous potential burden with possibly appealable
consequences.  I think this is a terrible idea.

It's this ¶ in particular that makes me worried:

   IETF consensus, with respect to this meeting Venue selection process
   is judged via standard IETF process and not by any other means, e.g.,
   surveys.  Surveys are used to gather information related to meeting
   venues, but not to measure consensus or to be reported as
   consensus.

If the below is what's meant instead, I can live with it (though I
think it could in that case be removed as it is already determined
elsewhere):

   IETF consensus, with respect to the meeting venue selection process
   herein outlined, is judged according to standard IETF process and
   not by any other means, e.g., surveys.  Surveys are used to gather
   information related to Venues, but not to measure consensus
   or to be reported as consensus.  By the same token, Venue decisions
   are not themselves subject to IETF consensus, and are instead
   decisions taken by the IAOC.

**Comment by eckelcu** [comment]
Consensus in room to remove text.
