### ISSUE TITLE
Clarity on definitions re hotel rooms and the facility in Section 3

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#5]
From AJS:

I'm not sure what to make of the definition in §3 where hotel rooms
might or might not be part of Facility.  This seems strange, though I
guess it's probably because of the IETF network?  If so, say that.
(But given that IETF Hotels and HQ Hotel are defined, this seems
wrong.)

**Comment by eckelcu** [comment]
Eliot to work with Andrew offline on definitions and bring proposal back to the list

**Comment by elear** [comment]
Slightly tweeked as follows:

>             The building that houses
>             meeting rooms and associated resources.  It may also
>             house an IETF Hotel or the Headquarters Hotel.
