### ISSUE TITLE
Clarity of responsibility

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#7]
From AJS:

I think that §§4.4 and 4.7 could be a whole lot clearer that the
responsibility for Venue selection rests ultimately with the IAOC and
that it's those people about whom IETF participants should complain to
the nomcom, if and when needed.

**Comment by eckelcu** [comment]
Add this as introduction in section 1, taking Brian's proposal into account as well. Pete will get back to Eliot on Brian's text.

**Comment by elear** [comment]
The end of Section 1 already contains the following:


       While this document uses these terms and these meanings, it
        remains the responsibility of the IAOC to apply their best
        judgment. The IAOC accepts input and feedback both during the
    consultation process and later (for instance when there are changes in the
        situation at a chosen location). Any appeals remain subject to
        the provisions of BCP101.

Added the following:


        As always, the community is encouraged to provide direct feedback to the
        NOMCOM, IESG, and IAB regarding the discharge of the IAOC's
        performance.

Also, the first paragraph in the introduction is rewritten as follows:

       The IAOC has responsibility for arranging IETF plenary meeting venue
        selection and operation.  The purpose of this document is to
        guide the IAOC in their selection of regions, cities, and
        facilities, and hotels.  The IAOC applies this guidance at
        different points in the process in an attempt to faithfully
        meet the requirements of the IETF community.  We specify a set
        of general criteria for venue selection and several requirements for
        transparency and community consultation.
