### ISSUE TITLE
Concurrent objection?

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#9]
In §5.2, should we provide a period for a concurrent objection to the
posted list?  That is, it'd be nice if there were a way for people to
say, "I know you're already investigating this place.  I still have
concerns, so please look into…"  I am of two minds about this, so
that's why this is a question and not a claim that we should.

**Comment by eckelcu** [comment]
Indicate that community responses (step b) can come in continuously

**Comment by elear** [comment]
Text to be included in section 5.2:

> The consultation may overlap with the previous step (identification).
